CREATE TABLE IF NOT EXISTS odp (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nama TEXT NOT NULL UNIQUE,
    lokasi TEXT NOT NULL,
    deskripsi TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE pelanggan ADD COLUMN odp_id INTEGER REFERENCES odp(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_pelanggan_odp_id ON pelanggan(odp_id);
